version: '3'
services:
  dsiprouter:
    build: 
      context: .
      dockerfile: docker/dsiprouter/dockerfile
    image: dopensource/dsiprouter
    volumes:
      - .:/opt/dsiprouter
    ports:
      - "5000"
    environment:
      - ENV=PROD
      - DSIP_USER=admin
      - DSIP_PASS=admin
      - DSIP_DEBUG=True
      - KAM_DB_HOST=dsiprouter-mysql
      - KAM_DB_TYPE=mysql 
      - KAM_DB_PORT=3306
      - KAM_DB_NAME=kamailio
      - KAM_DB_USER=kamailio
      - KAM_DB_PASS=kamailiorw
    depends_on: 
      - dsiprouter-mysql
    command: ["./containers/dsiprouter/wait-for-dsiprouter-mysql.sh","dsiprouter-mysql","python","dsiprouter.py","runserver"]
  
  kamailio:
    image: kamailio/kamailio:5.3.8-trusty
    restart: unless-stopped
    container_name: kamailio
    volumes:
      - .:/opt/dsiprouter
    ports:
      - "5060/udp:5060/udp"
      - "5060:5060"
    depends_on: 
      - dsiprouter-mysql

  dsiprouter-mysql:
    image: mysql:5.7
    volumes:
      - /tmp/dbdata:/var/lib/mysql
      - ./testing/sql/v0.60+ent:/docker-entrypoint-initdb.d/
    ports:
      - "3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=kamailio
      - MYSQL_PASSWORD=kamailiorw
      - MYSQL_DATABASE=kamailio
    healthcheck:
      test: mysql --user=root -e "select * from kamailio.dr_gateways"
      timeout: 45s
      retries: 5

  frontend:
      restart: unless-stopped
      image: staticfloat/nginx-certbot
      ports:
          - 80:80/tcp
          - 443:443/tcp
      environment:
          CERTBOT_EMAIL: owner@company.com
      volumes:
        - ./conf.d:/etc/nginx/user.conf.d:ro
        - letsencrypt:/etc/letsencrypt
volumes:
    letsencrypt:
